# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Sanjeev kumar Badrinath
title: DevOps Engineer - Infrastructure Automation
email: sanjeevkumarrao@gmail.com
phone: +61-470350214
website: www.github.com/sanjeevkumarrao/resume

# Social links
twitter_username: sanjeevkumarrao
github_username:  sanjeevkumarrao
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: sanjeevkumar-badrinath
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/sanjeev.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Sanjeev and I have around 10 years of software engineering experience. I'm an Automation Engineer with extensive knowledge in Chef framework, Automation scripts using Ruby and Shell. I started my career as a project engineer in Wipro Technologies and worked on various different technologies in both front end and server side technologies. Currently, I am working on an end-to-end infrastructure automation project in SAP Australia. I am an IBM certified worklight mobile application developer with a hands-on experience in JQuery mobile, Ionic Framework, Angular JS, and NodeJS.

  My expertise include:
    - Chef Framework
    - Chef vault
    - Jenkins
    - Ruby
    - MongoDB
    - NodeJS
    - AngularJS
    - HTML5
    - CSS3
    - Javascript
    - REST APIs
    - GitHub Integration and Hooks Maintainance

# Experience Section
# experience_title: My Experience

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Other than work, I am interested in IoT and keen to learn new stuffs like
   - Home Automation using Raspberry PI
   - Arduino coding

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
